### ISSUE TITLE
Is it possible to integrated with ActiveJob

### ISSUE THREAD

**Issue by simoniong** [guilleiguaran/fakeredis#244]
Just wonder if we could integrated this in-memory redis compatible gem with ActiveJob, and then we don't need Redis instance as a dependence inside test suite, which should speed up test cases in theory.

**Comment by guilleiguaran** [comment]
Thank you very much for the suggestion! 

For rails I believe it is desirable to test against an actual Redis instance since there are multiple features including ActiveJob, ActionCable and ActiveSupport Cache store, besides that we can use Docker to run the whole test suite: https://github.com/rails/rails/blob/0169d15bc7ec4557971d6ac6120e48b2cac9c407/.devcontainer/Dockerfile
