### ISSUE TITLE
Inconsistency between redis and fakeredis on `exists` method

### ISSUE THREAD

**Issue by jkojro** [guilleiguaran/fakeredis#265]
Redis.new.exists('nonexisting_key') on production will return `0` while Fakeredis will return `nil`

**Comment by carlost** [comment]
Looking at the last tag for the redis-db ruby client: 

https://github.com/redis/redis-rb/blob/5dd7df9310b1bac97b4ae0385faf7ba6c0fee1d2/lib/redis.rb#L608-L614

Looks like the redis client expects 0 for "does not exist" and greater than zero for "does exist".  I can't find docs on what the driver should look like.

And it looks like this issue was resolved by a commit back in August: https://github.com/guilleiguaran/fakeredis/pull/247

we just haven't had a release of fakeredis in over a year

**Comment by carlost** [comment]
and here are the docs: https://redis.io/commands/exists

**Comment by arthurchui** [comment]
+1

**Comment by rikas** [comment]
+1

**Comment by TimCannady** [comment]
+1

**Comment by lebeerman** [comment]
+1

**Comment by guilleiguaran** [comment]
Fixed in #247
